### ISSUE TITLE
On different networks (`mainnet` vs `testnet`) and environments (`production` vs `staging`)

### ISSUE THREAD

**Issue by thomaseizinger** [opendexnetwork/opendex.app#25]
## Requirements

1. Not every swap provider supports every network
2. It needs to be clear to users, which network they are currently using
3. We should be able to test new code on mainnet before making it generally available

## Assumptions

1. We don't automatically deploy to production as things are merged into main but instead, this is a dedicated step.

## Proposal

1. The current network is a runtime configuration

- I think it is preferable to have a "universal" build of the app that can run in any environment. If we opt to some form of have "staging" environment, a universal build would allow us to promote the exact same artifacts from the staging environment to prod, without requiring a rebuild.
- We will need to add some infrastructure for swap providers to check the current network and signal whether or not they are compatible with that. A react `Context` sounds like the right thing here.

2. The user can select the current network

3. Have `staging.opendex.app` as a CD target for everything that gets merged into main

4. Default the network based on the URL

This would allow us to by default have `mainnet` on `opendex.app` and `testnet` on `staging.opendex.app`.

## Possible usecases

If we implement the above, the following things become possible:

- A swap provider **without a public testnet** (looking at you, Liquid) can test new code (read: merged to main) before making it generally available (read: released). One can test this by simply selecting "mainnet" on `staging.opendex.app`.
- We can leverage netlify's branch-deploys which can deploy the code of a PR before it is merged. This allows us to test a feature before even merging it into main.
- Users can try out / test new features (on `staging.opendex.app`) before they are made generally available. Again, "testing" here is not restricted to using testnet. One can easily test on mainnet.

**Comment by BitcoinOG** [comment]
Thanks for the comprehensive write-up and agree with practically all of the above.

In summary we'd have:
- `staging.opendex.app` - automatically deployed from latest `main` + testnet/mainnet selector (default to testnet)
- `opendex.app` - automatically (or manually) deployed from latest `release` tag + testnet/mainnet selector (default to mainnet)
- feature branches should be deployed manually to a separate domain imo
- Global pair/network on/off config, e.g. frontend should show "not available on this network" for all L-BTC pairs on testnet

**Comment by michael1011** [comment]
Sounds good to me! I can start implementing this and have an early PR open by Monday latest.

I am not sure I understand the benefit of having a "universal" build over setting environment variables when building. In the end the only differences between mainnet and testnet are things like network constants, API URLs and block explorer links, right? @thomaseizinger

**Comment by thomaseizinger** [comment]
> Sounds good to me! I can start implementing this and have an early PR open by Monday latest.

That would be amazing!

> I am not sure I understand the benefit of having a "universal" build over setting environment variables when building though. In the end the only differences between mainnet and testnet are things like network constants, API URLs and block explorer links, right? @thomaseizinger

Well, if you want to have a runtime switch (with a dropdown or something), you can't really decide during buildtime what `BITCOIN_BLOCKEXPLORER_API_ENDPOINT` is. You can have two:

- `BITCOIN_MAINNET_BLOCKEXPLORER_API_ENDPOINT`
- `BITCOIN_TESTNET_BLOCKEXPLORER_API_ENDPOINT`

if you want them to be configurable overall (like switching from blockstream.info to something else).

Like I already hinted in the original post, we probably want to have a React context that contains the currently selected network. Based on that, all components should switch between the different constants, API URLs etc.
